server:
  port: 8081


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: oauth2-client-app
            clientSecret: sullSQEYzD9jLweP4wAkzUyIMuXzjm57
            clientName: aouth2-client-app
            redirectUri: http://localhost:8081/login/oauth2/code/keycloak #/login/oauth2/code은 security에서 자동 생성 가능
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,profile,email

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            tokenUri:
            issuerUri:
            userInfoUri:
            jwkSetUri:
            userNameAttribute:
