#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: localhost:8080
#        username: root
#        password: root

server:
  port: 8081
spring:
  security:
    user:
      name: user
      password: user